apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: wearables-worker-scaler
spec:
  scaleTargetRef:
    name: wearables-background-tasks
  pollingInterval: 5
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: redis-streams
      metadata:
        address: redis-13702.fcrce259.eu-central-1-3.ec2.cloud.redislabs.com:13702
        stream: taskiq
        consumerGroup: taskiq
        lagCount: "300"
        databaseIndex: "0"
      authenticationRef:
        name: redis-trigger-auth
