apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: wearables-worker-scaler
spec:
  scaleTargetRef:
    name: wearables-background-tasks
  pollingInterval: 5
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: rabbitmq
      metadata:
        protocol: http
        queueName: taskiq-wearables
        mode: QueueLength
        value: "300"
        vhostName: yuqoowqn
      authenticationRef:
        name: rabbitmq-trigger-auth
