apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-messaging
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hello-world-messaging
  template:
    metadata:
      labels:
        app: hello-world-messaging
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      terminationGracePeriodSeconds: 75
      containers:
        - name: hello-world-messaging
          command: ["poetry", "run", "uvicorn", "hello_world.messaging.main:app", "--host", "0.0.0.0", "--port", "8001", "--workers", "1"]
          envFrom:
            - configMapRef:
                name: hello-world-config
            - secretRef:
                name: hello-world-secrets
          env:
            - name: FASTSTREAM_RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-auth
                  key: RABBITMQ_URL
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-auth
                  key: SENTRY_DSN
          ports:
            - containerPort: 8001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
