FROM python:3.14-slim
WORKDIR /app

ENV POETRY_VERSION=1.8.3
RUN pip install poetry==$POETRY_VERSION

COPY pyproject.toml poetry.lock poetry.toml ./
RUN poetry install --no-root

COPY wearables/ ./wearables/
COPY tests/ ./tests/
COPY pytest.ini ./
