apiVersion: batch/v1
kind: Job
metadata:
  name: wearables-postgres-migration
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: wearables-pool
      containers:
        - name: migration
          image: wearables
          imagePullPolicy: Always
