apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
        - name: migration
          command: ["poetry", "run", "alembic", "upgrade", "expand@head"]
          envFrom:
            - configMapRef:
                name: hello-world-config
            - secretRef:
                name: hello-world-secrets
