services:
  postgresdb:
    image: timescale/timescaledb:latest-pg17
    container_name: postgresdb
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    configs:
      - source: init_sql
        target: /docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer:v1.25.1-p0
    container_name: pgbouncer
    ports:
      - "15433:5432"
    depends_on:
      postgresdb:
        condition: service_healthy
    command: ["pgbouncer", "/etc/pgbouncer/pgbouncer.ini"]
    configs:
      - source: pgbouncer_ini
        target: /etc/pgbouncer/pgbouncer.ini
      - source: pgbouncer_userlist
        target: /etc/pgbouncer/userlist.txt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgresdb_data:

configs:
  init_sql:
    content: |
      CREATE DATABASE wearables;
  pgbouncer_ini:
    content: |
      [databases]
      wearables = host=postgresdb port=5432
      [pgbouncer]
      listen_addr = 0.0.0.0
      listen_port = 5432
      auth_file = /etc/pgbouncer/userlist.txt
      auth_type = md5
      pool_mode = transaction
      ignore_startup_parameters = extra_float_digits
      max_prepared_statements = 20
      admin_users = postgres
  pgbouncer_userlist:
    content: |
      "postgres" "postgres"
