[pytest]
asyncio_default_fixture_loop_scope = session
addopts = --import-mode=importlib
testpaths =
    src/libs/tests
    src/services/hello_world/tests
    src/services/api_gateway/tests
    src/services/wearables/tests
