apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
