apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbouncer-config
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    name: gcp-cluster-store
    kind: ClusterSecretStore
  target:
    name: pgbouncer-config
    creationPolicy: Owner
  data:
    - secretKey: pgbouncer.ini
      remoteRef:
        key: pgbouncer-ini
    - secretKey: userlist.txt
      remoteRef:
        key: pgbouncer-userlist
