apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eshop-test-wildcard-tls
spec:
  secretName: eshop-test-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.eshop-test.com"
    - "eshop-test.com"
