apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-http
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never
