controller:
  replicaCount: 2
  config:
    entries:
      upstream-keepalive-timeout: "60"
  service:
    loadBalancerIP: "34.159.106.171"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/component: controller
          topologyKey: kubernetes.io/hostname
