apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  labels:
    app: redisinsight
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redis/redisinsight:v3.0.3
          ports:
            - containerPort: 5540
          volumeMounts:
            - name: redisinsight-data
              mountPath: /data
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5540
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5540
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: redisinsight-data
          persistentVolumeClaim:
            claimName: redisinsight-data
