apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-auth
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    name: gcp-cluster-store
    kind: ClusterSecretStore
  target:
    name: redis-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: redis-password
