apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  labels:
    app: migration
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  activeDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: migration
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              memory: "160Mi"
