apiVersion: batch/v1
kind: Job
metadata:
  name: wearables-postgres-contract-migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: wearables
          imagePullPolicy: Always
