apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    name: gcp-cluster-store
    kind: ClusterSecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  # NOTE @sosov: Placeholder for future service-specific secrets.
  data: []
