apiVersion: apps/v1
kind: Deployment
metadata:
  name: wearables-messaging
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: wearables-messaging
          image: wearables:latest
          imagePullPolicy: Never
