apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-store
spec:
  provider:
    gcpsm:
      projectID: eshop-test-485206
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: eso-ksa
            namespace: external-secrets
