apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: hello-world
                topologyKey: kubernetes.io/hostname
      containers:
        - name: hello-world
          image: hello-world
          imagePullPolicy: Always
