apiVersion: apps/v1
kind: Deployment
metadata:
  name: wearables-messaging
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: wearables-messaging
          image: wearables
          imagePullPolicy: Always
