apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: wearables-worker-scaler
spec:
  scaleTargetRef:
    name: wearables-messaging
  pollingInterval: 5
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: redis-streams
      metadata:
        address: redis-18185.crce275.eu-west3-1.gcp.cloud.redislabs.com:18185
        stream: taskiq
        consumerGroup: taskiq
        lagCount: "300"
        databaseIndex: "0"
      authenticationRef:
        name: redis-trigger-auth
