[group('run')]
run-http:
    poetry run uvicorn hello_world.http.main:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 75

[group('run')]
run-faststream-worker:
    FASTSTREAM_CLI_RICH_MODE=none poetry run faststream run hello_world.messaging.main:app
