apiVersion: apps/v1
kind: Deployment
metadata:
  name: wearables
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: wearables
          image: wearables:latest
          imagePullPolicy: Never
