apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-http
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: hello-world
          image: hello-world:latest
          imagePullPolicy: Never
