apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: redis-exporter
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
    - port: 9121
      interval: 30s
      path: /metrics
