apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wearables-secrets
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    name: gcp-cluster-store
    kind: ClusterSecretStore
  target:
    name: wearables-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DIRECT_DB_URL
      remoteRef:
        key: wearables-postgres-direct-db-url
