# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello_world.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hello_world.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hello_world.proto\x12\x1agrpc_protos.v1.hello_world\"\x10\n\x0eGetHostRequest\"\x1f\n\x0fGetHostResponse\x12\x0c\n\x04host\x18\x01 \x01(\t2w\n\x11HelloWorldService\x12\x62\n\x07GetHost\x12*.grpc_protos.v1.hello_world.GetHostRequest\x1a+.grpc_protos.v1.hello_world.GetHostResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_world_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETHOSTREQUEST']._serialized_start=49
  _globals['_GETHOSTREQUEST']._serialized_end=65
  _globals['_GETHOSTRESPONSE']._serialized_start=67
  _globals['_GETHOSTRESPONSE']._serialized_end=98
  _globals['_HELLOWORLDSERVICE']._serialized_start=100
  _globals['_HELLOWORLDSERVICE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
