apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: redis-exporter
          env:
            - name: REDIS_ADDR
              value: "redis://redis-13702.fcrce259.eu-central-1-3.ec2.cloud.redislabs.com:13702"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: password
