apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: redis-exporter
          env:
            - name: REDIS_ADDR
              value: "redis://redis-18185.crce275.eu-west3-1.gcp.cloud.redislabs.com:18185"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: password
