apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hello-world-secrets
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    name: gcp-cluster-store
    kind: ClusterSecretStore
  target:
    name: hello-world-secrets
    creationPolicy: Owner
  data:
    - secretKey: SENTRY_DSN
      remoteRef:
        key: hello-world-sentry-dsn
    - secretKey: FASTSTREAM_REDIS_URL
      remoteRef:
        key: hello-world-faststream-redis-url
