"""add wearable_event table

Revision ID: 177032a51f43
Revises:
Create Date: 2026-02-11 21:23:35.475966
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from libs.alembic_ext.timescale_ops import (
    ChunkIntervalEnum,
    CompressAfterEnum,
    add_compression_policy,
    create_hypertable,
    set_compression,
)

revision: str = "177032a51f43"
down_revision: Union[str, None] = "c9373c730ebf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "wearable_event",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("biomarker_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", "timestamp"),
    )
    op.create_index("ix_wearable_event_timestamp", "wearable_event", ["timestamp"], unique=False)

    create_hypertable(
        table_name="wearable_event",
        time_column="timestamp",
        chunk_interval=ChunkIntervalEnum.ONE_DAY,
    )
    set_compression(
        table_name="wearable_event",
        segment_by="user_id",
        order_by="timestamp DESC",
    )
    add_compression_policy(
        table_name="wearable_event",
        compress_after=CompressAfterEnum.SEVEN_DAYS,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wearable_event_timestamp", table_name="wearable_event")
    op.drop_table("wearable_event")
    # ### end Alembic commands ###
