apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: wearables-http
spec:
  selector:
    matchLabels:
      app: wearables-http
  endpoints:
    - port: 8000
      interval: 30s
      path: /metrics
