name: Deploy to Test EU

on:
  push:
    branches:
      - "test/**"

permissions:
  contents: read
  id-token: write

jobs:
  apply-infrastructure-secrets:
    uses: ./.github/workflows/called-apply-infrastructure-secrets.yaml
    with:
      environment: test-eu
    secrets: inherit

  publish-libs:
    needs: [apply-infrastructure-secrets]
    uses: ./.github/workflows/called-publish-libs.yaml
    with:
      environment: test-eu
    secrets: inherit

  deploy-infrastructure:
    needs: [apply-infrastructure-secrets]
    uses: ./.github/workflows/called-deploy-infrastructure.yaml
    with:
      environment: test-eu
    secrets: inherit

  deploy-api-gateway:
    needs: [deploy-infrastructure, publish-libs]
    uses: ./.github/workflows/called-deploy-service-to-gke.yaml
    with:
      environment: test-eu
      service_name: api-gateway
      service_path: src/services/api_gateway
      run_postgres_migrations: false

    secrets: inherit

  deploy-hello-world:
    needs: [deploy-infrastructure, publish-libs]
    uses: ./.github/workflows/called-deploy-service-to-gke.yaml
    with:
      environment: test-eu
      service_name: hello-world
      service_path: src/services/hello_world
      run_postgres_migrations: false

    secrets: inherit

  deploy-wearables:
    needs: [deploy-infrastructure, publish-libs]
    uses: ./.github/workflows/called-deploy-service-to-gke.yaml
    with:
      environment: test-eu
      service_name: wearables
      service_path: src/services/wearables
      run_postgres_migrations: true
      run_background_tasks_deployment: true

    secrets: inherit
