name: Deploy to Test EU

on:
  push:
    branches:
      - "test/**"

permissions:
  contents: read
  id-token: write

jobs:
  apply-infrastructure-secrets:
    uses: ./.github/workflows/called-apply-infrastructure-secrets.yaml
    with:
      environment: test-eu
    secrets: inherit

  publish-messaging-contracts:
    needs: [apply-infrastructure-secrets]
    uses: ./.github/workflows/called-publish-python-package.yaml
    with:
      environment: test-eu
      package_path: src/messaging_contracts
    secrets: inherit

  publish-grpc-protos:
    needs: [apply-infrastructure-secrets]
    uses: ./.github/workflows/called-publish-python-package.yaml
    with:
      environment: test-eu
      package_path: src/grpc_protos
    secrets: inherit

  publish-rabbitmq-topology:
    needs: [publish-messaging-contracts]
    uses: ./.github/workflows/called-publish-python-package.yaml
    with:
      environment: test-eu
      package_path: src/rabbitmq_topology
    secrets: inherit

  publish-libs:
    needs: [publish-rabbitmq-topology]
    uses: ./.github/workflows/called-publish-python-package.yaml
    with:
      environment: test-eu
      package_path: src/libs
    secrets: inherit

  deploy-infrastructure:
    needs: [apply-infrastructure-secrets]
    uses: ./.github/workflows/called-deploy-infrastructure.yaml
    with:
      environment: test-eu
    secrets: inherit

  deploy-rabbitmq-topology:
    needs: [deploy-infrastructure, publish-rabbitmq-topology]
    uses: ./.github/workflows/called-deploy-rabbitmq-topology.yaml
    with:
      environment: test-eu
    secrets: inherit

  deploy-api-gateway:
    needs: [deploy-rabbitmq-topology, publish-libs, publish-grpc-protos]
    uses: ./.github/workflows/called-deploy-service-to-gke.yaml
    with:
      environment: test-eu
      service_name: api-gateway
      service_path: src/services/api_gateway
      run_postgres_migrations: false
      run_background_tasks_deployment: false
      run_faststream_deployment: false

    secrets: inherit

  deploy-hello-world:
    needs: [deploy-rabbitmq-topology, publish-libs, publish-grpc-protos]
    uses: ./.github/workflows/called-deploy-service-to-gke.yaml
    with:
      environment: test-eu
      service_name: hello-world
      service_path: src/services/hello_world
      run_postgres_migrations: true
      run_background_tasks_deployment: false
      run_faststream_deployment: true
      run_http_deployment: false
      run_grpc_deployment: true

    secrets: inherit

  deploy-wearables:
    needs: [deploy-rabbitmq-topology, publish-libs]
    uses: ./.github/workflows/called-deploy-service-to-gke.yaml
    with:
      environment: test-eu
      service_name: wearables
      service_path: src/services/wearables
      run_postgres_migrations: true
      run_background_tasks_deployment: true
      run_faststream_deployment: true

    secrets: inherit
