name: Deploy to Test EU

on:
  push:
    branches:
      - "test/**"

permissions:
  contents: read
  id-token: write

jobs:
  publish-libs:
    uses: ./.github/workflows/called-publish-libs.yaml
    with:
      environment: test-eu
    secrets: inherit

  deploy-infrastructure:
    uses: ./.github/workflows/called-deploy-infrastructure.yaml
    with:
      environment: test-eu
    secrets: inherit

  deploy-api-gateway:
    needs: [deploy-infrastructure, publish-libs]
    uses: ./.github/workflows/called-deploy-to-gke.yaml
    with:
      environment: test-eu
      service_name: api-gateway
      service_path: src/services/api_gateway
    secrets: inherit

  deploy-hello-world:
    needs: [deploy-infrastructure, publish-libs]
    uses: ./.github/workflows/called-deploy-to-gke.yaml
    with:
      environment: test-eu
      service_name: hello-world
      service_path: src/services/hello_world
    secrets: inherit
